version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5273:80"
    depends_on:
      - main
      - auth

  main:
    build:
      context: ./backend/main-server
    ports:
      - "3000:3000"
    depends_on:
      - db

  auth:
    build:
      context: ./backend/auth-server
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  