version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    environment:
      - NODE_ENV=development

  main-server:
    build:
      context: .
      dockerfile: backend/main-server/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./backend/main-server:/app
      - ./shared:/app/shared
    environment:
      - NODE_ENV=development

  auth-server:
    build:
      context: .
      dockerfile: backend/auth-server/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./backend/auth-server:/app
      - ./shared:/app/shared
    environment:
      - NODE_ENV=development

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRECT=${ACCESS_TOKEN_SECRECT}
      - REFRESH_TOKEN_SECRECT=${REFRESH_TOKEN_SECRECT}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - ACCESS_TOKEN_SECRET_EXPIRES_IN=${ACCESS_TOKEN_SECRET_EXPIRES_IN}
    
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: